@startuml
' see https://plantuml-documentation.readthedocs.io/en/latest/formatting/all-skin-params.html

' colors
skinparam ArrowColor #009DDC
skinparam ArrowFontColor #009DDC
skinparam BackgroundColor #FFFFFF
skinparam BorderColor #CCCCCC
skinparam DefaultFontColor #000000

' typography
skinparam DefaultFontName Roboto
skinparam DefaultFontSize 13
skinparam DefaultFontStyle normal
skinparam DefaultMonospacedFontName "Roboto Mono"
skinparam DefaultTextAlignment center

' layout
skinparam ArrowThickness 2
skinparam ResponseMessageBelowArrow true
skinparam RoundCorner 20
skinparam Shadowing false

skinparam Sequence {
	LifeLineBackgroundColor #CCCCCC
	LifeLineBorderColor #CCCCCC
	LifeLineBorderThickness 3
	MessageAlign center

	ParticipantBackgroundColor #EEEEEE
	ParticipantBorderColor #AAAAAA
}
@enduml
