@startuml
!include ./logo.puml

right footer
<font color=darkgray>© All rights reserved <$sigwin,scale=0.15,color=darkblue></font>
rectangle Sample [
    Triangle
    ' Reference sprite with name triangle
    <$sigwin>
]
endfooter
@enduml
